import React, { useState, useEffect, useRef } from 'react';
import Editor from '@monaco-editor/react';
import JSZip from 'jszip';
import { 
  Play, RotateCcw, Monitor, FileCode, CheckCircle, Terminal as TerminalIcon, 
  Download, Plus, FolderPlus, Trash2, Folder, FolderOpen, File, 
  Edit3, ChevronRight, ChevronDown, RefreshCw, Layers, ShieldCheck, AlertCircle,
  Sparkles
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { VirtualFile, VirtualFolder } from '../types';

interface CodeWorkspaceProps {
  code: string;
  language: string;
  description?: string;
  onCodeChange: (newCode: string) => void;
  files: VirtualFile[];
  setFiles: React.Dispatch<React.SetStateAction<VirtualFile[]>>;
  folders: VirtualFolder[];
  setFolders: React.Dispatch<React.SetStateAction<VirtualFolder[]>>;
  selectedFileId: string;
  setSelectedFileId: (id: string) => void;
}

export const DEFAULT_FILES: VirtualFile[] = [
  {
    id: 'f1',
    name: 'index.html',
    path: 'index.html',
    language: 'html',
    content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>App</title>
</head>
<body>
  
</body>
</html>`
  }
];

export const DEFAULT_FOLDERS: VirtualFolder[] = [];


export default function CodeWorkspace({
  code,
  language,
  description,
  onCodeChange,
  files,
  setFiles,
  folders,
  setFolders,
  selectedFileId,
  setSelectedFileId,
}: CodeWorkspaceProps) {
  const [activeTab, setActiveTab] = useState<'editor' | 'preview' | 'terminal'>('editor');

  // UI States
  const [expandedFolders, setExpandedFolders] = useState<Record<string, boolean>>({ 'src': true });
  const [newItemType, setNewItemType] = useState<'file' | 'folder' | null>(null);
  const [newItemParentPath, setNewItemParentPath] = useState<string>('');
  const [newItemName, setNewItemName] = useState<string>('');
  const [renamingItemId, setRenamingItemId] = useState<{id: string, type: 'file' | 'folder'} | null>(null);
  const [renamingItemValue, setRenamingItemValue] = useState<string>('');

  // Sandbox Live execution iframe
  const [iframeSrcDoc, setIframeSrcDoc] = useState('');
  const [logs, setLogs] = useState<string[]>([]);

  // Terminal Simulator State
  const [terminalHistory, setTerminalHistory] = useState<string[]>([
    'Welcome to Local Virtual Terminal (v1.8.0)',
    'Running isolated P2P micro-kernel inside browser context...',
    'Type "help" for a list of awesome commands.',
    ''
  ]);
  const [terminalInput, setTerminalInput] = useState<string>('');
  const terminalBottomRef = useRef<HTMLDivElement>(null);
  const terminalInputRef = useRef<HTMLInputElement>(null);


  // Sync to local storage
  useEffect(() => {
    localStorage.setItem('virtual_files', JSON.stringify(files));
  }, [files]);

  useEffect(() => {
    localStorage.setItem('virtual_folders', JSON.stringify(folders));
  }, [folders]);

  useEffect(() => {
    localStorage.setItem('virtual_selected_file_id', selectedFileId);
  }, [selectedFileId]);

  // Update selected file's content when active code changes in editor
  const handleEditorChange = (newVal: string) => {
    onCodeChange(newVal);
    setFiles(prev => prev.map(f => f.id === selectedFileId ? { ...f, content: newVal } : f));
  };

  // Sync external code generated by AI to the active file (or create new file if requested)
  useEffect(() => {
    if (code) {
      const activeFile = files.find(f => f.id === selectedFileId);
      if (activeFile && activeFile.content !== code) {
        setFiles(prev => prev.map(f => f.id === selectedFileId ? { ...f, content: code } : f));
      }
    }
  }, [code]);

  // When changing selected file, load its values
  const selectFile = (file: VirtualFile) => {
    setSelectedFileId(file.id);
    onCodeChange(file.content);
  };

  const getLanguageFromFilename = (filename: string): string => {
    const ext = filename.split('.').pop() || '';
    if (ext === 'html') return 'html';
    if (ext === 'css') return 'css';
    if (ext === 'js' || ext === 'jsx') return 'javascript';
    if (ext === 'ts' || ext === 'tsx') return 'typescript';
    if (ext === 'json') return 'json';
    if (ext === 'md') return 'markdown';
    return 'plaintext';
  };

  // New File/Folder logic
  const createItem = () => {
    if (!newItemName.trim()) return;

    const fullPath = newItemParentPath 
      ? `${newItemParentPath}/${newItemName.trim()}` 
      : newItemName.trim();

    if (newItemType === 'file') {
      const extension = newItemName.split('.').pop() || 'js';
      const lang = getLanguageFromFilename(newItemName);
      const newFile: VirtualFile = {
        id: 'file_' + Date.now(),
        name: newItemName.trim(),
        path: fullPath,
        language: lang,
        content: `// File: ${fullPath}\n\nexport function init() {\n  console.log("Initialized ${newItemName}");\n}`
      };
      setFiles(prev => [...prev, newFile]);
      setSelectedFileId(newFile.id);
      onCodeChange(newFile.content);
      addTerminalLog(`touch: Created file ${fullPath}`);
    } else {
      const newFolder: VirtualFolder = {
        id: 'folder_' + Date.now(),
        name: newItemName.trim(),
        path: fullPath
      };
      setFolders(prev => [...prev, newFolder]);
      setExpandedFolders(prev => ({ ...prev, [fullPath]: true }));
      addTerminalLog(`mkdir: Created folder ${fullPath}`);
    }

    setNewItemType(null);
    setNewItemName('');
  };

  // Delete file
  const deleteFile = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const fileToDelete = files.find(f => f.id === id);
    if (!fileToDelete) return;

    if (window.confirm(`Do you want to delete the file ${fileToDelete.path}?`)) {
      setFiles(prev => prev.filter(f => f.id !== id));
      addTerminalLog(`rm: Removed file ${fileToDelete.path}`);
      if (selectedFileId === id) {
        const remaining = files.filter(f => f.id !== id);
        if (remaining.length > 0) {
          setSelectedFileId(remaining[0].id);
          onCodeChange(remaining[0].content);
        } else {
          onCodeChange('');
        }
      }
    }
  };

  // Delete folder (and all its sub-files/folders)
  const deleteFolder = (folderPath: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (window.confirm(`Do you want to delete the folder ${folderPath} and all its contents?`)) {
      setFolders(prev => prev.filter(fol => fol.path !== folderPath && !fol.path.startsWith(folderPath + '/')));
      setFiles(prev => prev.filter(f => !f.path.startsWith(folderPath + '/')));
      addTerminalLog(`rm -rf: Removed folder ${folderPath}`);
    }
  };

  // Export full workspace as beautiful ZIP
  const exportAsZip = async () => {
    try {
      const zip = new JSZip();
      
      // Add files with their paths
      files.forEach(file => {
        zip.file(file.path, file.content);
      });

      const content = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = `academic_workspace_${Date.now()}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      addTerminalLog('zip: Workspace zipped successfully. Download triggered!');
    } catch (err: any) {
      console.error(err);
      alert('Error during ZIP archiving: ' + err.message);
    }
  };

  // Preview / Execution Sandbox logic
  const runWorkspace = () => {
    setLogs([]);
    const mainHtml = files.find(f => f.path === 'index.html');
    if (!mainHtml) {
      addLog('ERROR: index.html file not found.');
      return;
    }

    // Build absolute file mapping for client resolution inside sandbox
    // Inline resolver will bundle Javascript files and inject style sheets
    let processedHtml = mainHtml.content;

    // Resolve style sheets (inject styles from css files directly for complete simulation)
    files.forEach(file => {
      if (file.language === 'css') {
        const styleTag = `<style id="resolved-${file.name}">\n${file.content}\n</style>`;
        processedHtml = processedHtml.replace(
          new RegExp(`<link[^>]*href=["'](?:src/)?${file.name}["'][^>]*>`, 'gi'),
          styleTag
        );
      }
    });

    // Resolve script files and inject console catcher
    const consoleCatcher = `
      <script>
        const _log = console.log;
        const _error = console.error;
        window.console.log = function(...args) {
          window.parent.postMessage({ type: 'CONSOLE_LOG', data: args.join(' ') }, '*');
          _log.apply(console, args);
        };
        window.console.error = function(...args) {
          window.parent.postMessage({ type: 'CONSOLE_ERROR', data: args.join(' ') }, '*');
          _error.apply(console, args);
        };
        window.onerror = function(message, source, lineno, colno, error) {
          window.parent.postMessage({ type: 'CONSOLE_ERROR', data: message }, '*');
        };
      </script>
    `;

    // Inline Javascript imports for local sandbox
    files.forEach(file => {
      if (file.language === 'javascript') {
        // Find utils or relative exports, compile them in scope
        // Simple regex replace to strip 'import' / 'export' statements so it compiles easily in iframe global scope
        let strippedJs = file.content
          .replace(/import\s+.*?\s+from\s+['"].*?['"];?/g, '')
          .replace(/export\s+/g, '');

        const scriptTag = `<script>\n${strippedJs}\n</script>`;
        
        // Either replace index.js script src or inject
        if (file.name === 'index.js') {
          processedHtml = processedHtml.replace(
            /<script[^>]*src=["'](?:src\/)?index\.js["'][^>]*><\/script>/gi,
            scriptTag
          );
        } else {
          // Put helper utils before index.js
          processedHtml = consoleCatcher + `\n<script>\n${strippedJs}\n</script>\n` + processedHtml;
        }
      }
    });

    if (!processedHtml.includes(consoleCatcher)) {
      processedHtml = consoleCatcher + processedHtml;
    }

    setIframeSrcDoc(processedHtml);
    setActiveTab('preview');
    addLog('Workspace Sandbox compiled and rendered.');
  };

  const addLog = (msg: string) => {
    setLogs(prev => [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`]);
  };

  const addTerminalLog = (msg: string) => {
    setTerminalHistory(prev => [...prev, msg]);
  };

  // Iframe console hook
  useEffect(() => {
    const handleMessage = (e: MessageEvent) => {
      if (e.data && e.data.type === 'CONSOLE_LOG') {
        addLog(`LOG: ${e.data.data}`);
      } else if (e.data && e.data.type === 'CONSOLE_ERROR') {
        addLog(`ERROR: ${e.data.data}`);
      }
    };
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, []);

  // Sync active file with Monaco editor component value on change
  const currentFile = files.find(f => f.id === selectedFileId);

  // Terminal Simulator key handler
  const handleTerminalSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const cmd = terminalInput.trim();
    if (!cmd) return;

    setTerminalHistory(prev => [...prev, `user@localhost:~/workspace$ ${cmd}`]);
    executeTerminalCommand(cmd);
    setTerminalInput('');
  };

  const executeTerminalCommand = (line: string) => {
    const parts = line.split(' ');
    const command = parts[0].toLowerCase();
    const args = parts.slice(1);

    switch (command) {
      case 'help':
        addTerminalLog('Available commands:');
        addTerminalLog('  ls           - List files and folders');
        addTerminalLog('  cat [file]    - Show file contents');
        addTerminalLog('  touch [file]  - Create a new empty file');
        addTerminalLog('  mkdir [folder] - Create a new folder');
        addTerminalLog('  rm [file]     - Delete a file');
        addTerminalLog('  clear        - Clear the terminal screen');
        addTerminalLog('  node [file]   - Execute JS file and output console.log results');
        addTerminalLog('  zip          - Export entire project as a ZIP file');
        addTerminalLog('  info         - Show information about the virtual environment');
        break;

      case 'ls':
        addTerminalLog('Directory structure of: ~/workspace');
        folders.forEach(fol => {
          addTerminalLog(`📁  ${fol.path}/`);
        });
        files.forEach(f => {
          addTerminalLog(`📄  ${f.path}  (${f.content.length} bytes)`);
        });
        break;

      case 'cat':
        if (!args[0]) {
          addTerminalLog('Error: Please specify a filename (e.g., cat index.html)');
        } else {
          const target = files.find(f => f.path === args[0] || f.name === args[0]);
          if (target) {
            addTerminalLog(`--- ${target.path} ---`);
            const lines = target.content.split('\n');
            lines.forEach(l => addTerminalLog(l));
          } else {
            addTerminalLog(`cat: ${args[0]}: File not found.`);
          }
        }
        break;

      case 'touch':
        if (!args[0]) {
          addTerminalLog('touch: Filename not specified.');
        } else {
          const newF: VirtualFile = {
            id: 'file_' + Date.now(),
            name: args[0],
            path: args[0],
            language: getLanguageFromFilename(args[0]),
            content: `// touch: created at ${new Date().toLocaleString()}`
          };
          setFiles(prev => [...prev, newF]);
          addTerminalLog(`touch: Created file ${args[0]}`);
        }
        break;

      case 'mkdir':
        if (!args[0]) {
          addTerminalLog('mkdir: Folder name not specified.');
        } else {
          const newFol: VirtualFolder = {
            id: 'folder_' + Date.now(),
            name: args[0],
            path: args[0]
          };
          setFolders(prev => [...prev, newFol]);
          addTerminalLog(`mkdir: Created folder ${args[0]}`);
        }
        break;

      case 'rm':
        if (!args[0]) {
          addTerminalLog('rm: Target not specified.');
        } else {
          const found = files.find(f => f.path === args[0] || f.name === args[0]);
          if (found) {
            setFiles(prev => prev.filter(f => f.id !== found.id));
            addTerminalLog(`rm: Successfully deleted file ${found.path}`);
          } else {
            addTerminalLog(`rm: ${args[0]}: File not found.`);
          }
        }
        break;

      case 'node':
        if (!args[0]) {
          addTerminalLog('node: Please specify a file to run.');
        } else {
          const target = files.find(f => f.path === args[0] || f.name === args[0]);
          if (target) {
            addTerminalLog(`[NODE RUNNER] Executing ${target.path}...`);
            try {
              // Capture eval logs
              let consoleOutputs: string[] = [];
              const originalLog = console.log;
              console.log = (...m) => {
                consoleOutputs.push(m.join(' '));
              };

              // Simple evaluation sandbox
              // Strip imports/exports to execute smoothly
              const cleanEval = target.content
                .replace(/import\s+.*?\s+from\s+['"].*?['"];?/g, '')
                .replace(/export\s+/g, '');

              eval(cleanEval);
              console.log = originalLog;

              if (consoleOutputs.length === 0) {
                addTerminalLog('node: Execution finished with no console output.');
              } else {
                consoleOutputs.forEach(o => addTerminalLog(`> ${o}`));
              }
            } catch (err: any) {
              addTerminalLog(`node runner error: ${err.message}`);
            }
          } else {
            addTerminalLog(`node: ${args[0]}: File not found.`);
          }
        }
        break;

      case 'zip':
        exportAsZip();
        break;

      case 'clear':
        setTerminalHistory([]);
        break;

      case 'info':
        addTerminalLog('=== VIRTUAL SYSTEMS INFO ===');
        addTerminalLog(`Memory: Browser Indexed VFS`);
        addTerminalLog(`Active Files Count: ${files.length}`);
        addTerminalLog(`Active Folders Count: ${folders.length}`);
        addTerminalLog(`NodeJS virtualized interpreter: Yes`);
        addTerminalLog(`Local P2P Bridge: Activated`);
        addTerminalLog('============================');
        break;

      default:
        addTerminalLog(`bash: ${command}: command not found. Type "help" for a list.`);
    }
  };

  // Auto scroll terminal to bottom
  useEffect(() => {
    if (terminalBottomRef.current) {
      terminalBottomRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [terminalHistory]);

  return (
    <div className="h-full flex flex-col bg-slate-950 border border-slate-800/80 rounded-2xl overflow-hidden shadow-2xl relative">
      
      {/* IDE Top Bar Header */}
      <div className="bg-slate-900 px-4 py-3 border-b border-slate-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-3 shrink-0">
        
        {/* Left indicators */}
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-red-500"></div>
          <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
          <div className="w-3 h-3 rounded-full bg-green-500"></div>
          <span className="text-xs text-slate-400 font-mono ml-2 flex items-center gap-1.5 uppercase font-bold tracking-wider">
            <Layers className="w-4 h-4 text-cyan-400" />
            AWESchool Academic IDE
          </span>
        </div>

        {/* Tab Selection */}
        <div className="flex items-center gap-1.5 bg-slate-950/80 p-0.5 rounded-lg border border-slate-800 self-end sm:self-auto">
          <button
            onClick={() => setActiveTab('editor')}
            className={`px-3 py-1 text-[11px] font-bold rounded-md transition-all cursor-pointer flex items-center gap-1 ${
              activeTab === 'editor' ? 'bg-cyan-500/10 text-cyan-400' : 'text-slate-400 hover:text-white'
            }`}
          >
            <FileCode className="w-3.5 h-3.5" />
            Code
          </button>
          <button
            onClick={() => {
              runWorkspace();
              setActiveTab('preview');
            }}
            className={`px-3 py-1 text-[11px] font-bold rounded-md transition-all cursor-pointer flex items-center gap-1 ${
              activeTab === 'preview' ? 'bg-emerald-500/10 text-emerald-400' : 'text-slate-400 hover:text-white'
            }`}
          >
            <Monitor className="w-3.5 h-3.5" />
            Preview
          </button>
          <button
            onClick={() => setActiveTab('terminal')}
            className={`px-3 py-1 text-[11px] font-bold rounded-md transition-all cursor-pointer flex items-center gap-1 ${
              activeTab === 'terminal' ? 'bg-amber-500/10 text-amber-400' : 'text-slate-400 hover:text-white'
            }`}
          >
            <TerminalIcon className="w-3.5 h-3.5" />
            Terminal
          </button>
        </div>
      </div>

      {/* Main workspace splits: Left directory file manager, Right: Active Workspace content */}
      <div className="flex-1 flex min-h-0 relative">
        
        {/* Directory Explorer sidebar */}
        <div className="w-56 bg-slate-900/60 border-r border-slate-800/80 flex flex-col shrink-0 overflow-y-auto">
          
          {/* VFS Toolbar */}
          <div className="p-3 border-b border-slate-800/60 flex items-center justify-between">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">FILE TREE</span>
            <div className="flex gap-1">
              <button 
                onClick={() => {
                  setNewItemType('file');
                  setNewItemParentPath('');
                }}
                className="p-1 hover:bg-slate-800 rounded text-cyan-400 hover:text-white cursor-pointer"
                title="New file"
              >
                <Plus className="w-3.5 h-3.5" />
              </button>
              <button 
                onClick={() => {
                  setNewItemType('folder');
                  setNewItemParentPath('');
                }}
                className="p-1 hover:bg-slate-800 rounded text-amber-400 hover:text-white cursor-pointer"
                title="New folder"
              >
                <FolderPlus className="w-3.5 h-3.5" />
              </button>
              <button 
                onClick={exportAsZip}
                className="p-1 hover:bg-slate-800 rounded text-indigo-400 hover:text-white cursor-pointer animate-pulse"
                title="Download as ZIP"
              >
                <Download className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>

          {/* New file/folder inline prompt */}
          {newItemType && (
            <div className="p-2 bg-slate-950 border-b border-slate-800">
              <span className="text-[9px] text-slate-500 block mb-1 uppercase font-mono">
                Add new {newItemType === 'file' ? 'file' : 'folder'} {newItemParentPath ? `(in ${newItemParentPath})` : ''}
              </span>
              <div className="flex gap-1.5">
                <input 
                  type="text"
                  placeholder={newItemType === 'file' ? 'app.js' : 'src'}
                  value={newItemName}
                  onChange={(e) => setNewItemName(e.target.value)}
                  className="bg-slate-900 border border-slate-800 text-[11px] rounded px-1.5 py-0.5 w-full text-white font-mono focus:outline-none focus:border-cyan-500"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') createItem();
                  }}
                  autoFocus
                />
                <button 
                  onClick={createItem}
                  className="bg-cyan-600 hover:bg-cyan-500 text-[10px] font-bold px-2 rounded cursor-pointer"
                >
                  Ok
                </button>
              </div>
              <button 
                onClick={() => setNewItemType(null)}
                className="text-[9px] text-red-400 mt-1 block hover:underline"
              >
                Cancel
              </button>
            </div>
          )}

          {/* Core File Tree Render */}
          <div className="flex-1 p-2 space-y-1 overflow-y-auto">
            
            {/* Render Root Level Items */}
            {/* First: folders */}
            {folders.map(fol => (
              <div key={fol.id} className="space-y-0.5">
                <div 
                  onClick={() => {
                    setExpandedFolders(prev => ({ ...prev, [fol.path]: !prev[fol.path] }));
                  }}
                  className="flex items-center justify-between text-xs text-slate-300 font-medium px-1.5 py-1 rounded hover:bg-slate-800/50 cursor-pointer group"
                >
                  <div className="flex items-center gap-1.5">
                    {expandedFolders[fol.path] ? <ChevronDown className="w-3 h-3 text-slate-500" /> : <ChevronRight className="w-3 h-3 text-slate-500" />}
                    {expandedFolders[fol.path] ? <FolderOpen className="w-3.5 h-3.5 text-amber-400 shrink-0" /> : <Folder className="w-3.5 h-3.5 text-amber-400 shrink-0" />}
                    <span className="truncate">{fol.name}</span>
                  </div>
                  <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100">
                    <button 
                      onClick={(e) => {
                        e.stopPropagation();
                        setNewItemType('file');
                        setNewItemParentPath(fol.path);
                      }}
                      className="p-0.5 hover:bg-slate-700 rounded text-cyan-400"
                      title="Create file"
                    >
                      <Plus className="w-3 h-3" />
                    </button>
                    <button 
                      onClick={(e) => deleteFolder(fol.path, e)}
                      className="p-0.5 hover:bg-slate-700 rounded text-red-400"
                      title="Delete folder"
                    >
                      <Trash2 className="w-3 h-3" />
                    </button>
                  </div>
                </div>

                {/* Sub-items if folder is expanded */}
                {expandedFolders[fol.path] && (
                  <div className="pl-4 border-l border-slate-800/80 ml-3 space-y-0.5">
                    {files.filter(f => f.path.startsWith(fol.path + '/')).map(subF => (
                      <div
                        key={subF.id}
                        onClick={() => selectFile(subF)}
                        className={`flex items-center justify-between text-xs font-mono px-1.5 py-1 rounded cursor-pointer transition-all group ${
                          selectedFileId === subF.id 
                            ? 'bg-cyan-500/10 text-cyan-400 border-l border-cyan-500' 
                            : 'text-slate-400 hover:bg-slate-800/40 hover:text-slate-200'
                        }`}
                      >
                        <div className="flex items-center gap-1.5 truncate">
                          <File className="w-3 h-3 text-cyan-500 shrink-0" />
                          <span className="truncate">{subF.name}</span>
                        </div>
                        <button 
                          onClick={(e) => deleteFile(subF.id, e)}
                          className="opacity-0 group-hover:opacity-100 p-0.5 hover:bg-slate-700 rounded text-red-400"
                          title="Delete file"
                        >
                          <Trash2 className="w-3 h-3" />
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}

            {/* Then: root level files */}
            {files.filter(f => !f.path.includes('/')).map(f => (
              <div
                key={f.id}
                onClick={() => selectFile(f)}
                className={`flex items-center justify-between text-xs font-mono px-1.5 py-1.5 rounded cursor-pointer transition-all group ${
                  selectedFileId === f.id 
                    ? 'bg-cyan-500/10 text-cyan-400 border-l border-cyan-500' 
                    : 'text-slate-400 hover:bg-slate-800/40 hover:text-slate-200'
                }`}
              >
                <div className="flex items-center gap-1.5 truncate">
                  <File className="w-3.5 h-3.5 text-cyan-500 shrink-0" />
                  <span className="truncate">{f.name}</span>
                </div>
                <button 
                  onClick={(e) => deleteFile(f.id, e)}
                  className="opacity-0 group-hover:opacity-100 p-0.5 hover:bg-slate-700 rounded text-red-400"
                  title="Delete file"
                >
                  <Trash2 className="w-3 h-3" />
                </button>
              </div>
            ))}
          </div>

          {/* Quick Stats */}
          <div className="p-3 border-t border-slate-800 bg-slate-900/30">
            <div className="flex items-center gap-1 text-[10px] text-emerald-400 font-mono">
              <ShieldCheck className="w-3 h-3" />
              <span>P2P VFS • Sync</span>
            </div>
          </div>
        </div>

        {/* Dynamic Workspace Container */}
        <div className="flex-1 min-w-0 relative flex flex-col">
          
          {/* tab: Monaco editor */}
          {activeTab === 'editor' && (
            <div className="flex-1 min-h-0 relative">
              {currentFile ? (
                <Editor
                  height="100%"
                  language={currentFile.language}
                  theme="vs-dark"
                  value={currentFile.content}
                  onChange={(val) => handleEditorChange(val || '')}
                  options={{
                    minimap: { enabled: false },
                    fontSize: 13,
                    fontFamily: 'JetBrains Mono, Fira Code, monospace',
                    automaticLayout: true,
                    scrollBeyondLastLine: false,
                    lineNumbers: 'on',
                    padding: { top: 10, bottom: 10 }
                  }}
                />
              ) : (
                <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-500">
                  <AlertCircle className="w-12 h-12 text-slate-700 mb-2" />
                  <span>Select or create any file from the left list</span>
                </div>
              )}
            </div>
          )}

          {/* tab: Webpage Live Preview */}
          {activeTab === 'preview' && (
            <div className="flex-1 min-h-0 bg-slate-950 flex flex-col">
              {iframeSrcDoc ? (
                <iframe
                  srcDoc={iframeSrcDoc}
                  title="Code Workspace Preview"
                  className="flex-1 w-full bg-white rounded-t-lg border-none"
                  sandbox="allow-scripts"
                />
              ) : (
                <div className="flex-1 flex flex-col items-center justify-center text-slate-500 text-sm">
                  <Monitor className="w-12 h-12 text-slate-700 mb-2" />
                  <span>Result preview is not ready. Click "Run"</span>
                </div>
              )}

              {/* Console logs */}
              <div className="h-40 bg-slate-900 border-t border-slate-800/80 p-3 flex flex-col font-mono text-xs">
                <div className="flex items-center gap-1.5 text-slate-400 font-bold mb-1.5 border-b border-slate-800 pb-1.5 shrink-0">
                  <TerminalIcon className="w-3.5 h-3.5 text-yellow-500" />
                  <span>Sandbox Console Logs</span>
                </div>
                <div className="flex-1 overflow-y-auto space-y-1">
                  {logs.length === 0 ? (
                    <span className="text-slate-600 italic">Logs are empty...</span>
                  ) : (
                    logs.map((log, i) => (
                      <div key={i} className={`whitespace-pre-wrap ${
                        log.includes('ERROR:') ? 'text-red-400 animate-pulse' : log.includes('LOG:') ? 'text-cyan-400' : 'text-slate-500'
                      }`}>
                        {log}
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>
          )}

          {/* tab: Local Terminal Simulator */}
          {activeTab === 'terminal' && (
            <div className="flex-1 min-h-0 bg-slate-950 p-4 font-mono text-xs flex flex-col overflow-hidden">
              <div className="flex items-center justify-between text-slate-500 mb-2 border-b border-slate-800 pb-2">
                <span>MicroKernel P2P Node JS Sandbox</span>
                <span>Active path: ~/workspace</span>
              </div>
              
              {/* Output history */}
              <div className="flex-1 overflow-y-auto space-y-1.5 mb-2 text-slate-300 pr-1 select-text">
                {terminalHistory.map((item, i) => (
                  <div key={i} className="whitespace-pre-wrap leading-relaxed">
                    {item}
                  </div>
                ))}
                <div ref={terminalBottomRef} />
              </div>

              {/* Command input prompt */}
              <form onSubmit={handleTerminalSubmit} className="flex items-center gap-2 border-t border-slate-800 pt-2.5">
                <span className="text-cyan-400 font-bold shrink-0">user@localhost:~/workspace$</span>
                <input 
                  ref={terminalInputRef}
                  type="text"
                  value={terminalInput}
                  onChange={(e) => setTerminalInput(e.target.value)}
                  className="flex-1 bg-transparent border-none text-white font-mono focus:outline-none placeholder-slate-700"
                  placeholder={"Enter command (e.g. ls, cat index.html, help...)"}
                  autoFocus
                />
              </form>
            </div>
          )}

        </div>
      </div>

      {/* Control Footer */}
      <div className="bg-slate-900 px-4 py-2.5 border-t border-slate-800/80 flex items-center justify-between shrink-0">
        <span className="text-[10px] text-slate-500 font-mono">
          © AI Studio Monaco Engine • Virtual MicroKernel Sandbox Enabled
        </span>

        <div className="flex gap-2">
          <button
            onClick={() => {
              if (window.confirm('Restore original file system? This will delete your current changes.')) {
                setFiles(DEFAULT_FILES);
                setFolders(DEFAULT_FOLDERS);
                setSelectedFileId('f1');
                onCodeChange(DEFAULT_FILES[0].content);
                addTerminalLog('reset: File system reset to factory template.');
              }
            }}
            className="px-2.5 py-1.5 bg-slate-950 hover:bg-slate-800 border border-slate-800 hover:border-slate-700 text-xs text-slate-400 hover:text-white rounded-lg transition-all flex items-center gap-1 cursor-pointer"
            title="Clear / Restore File System"
          >
            <RotateCcw className="w-3.5 h-3.5" />
          </button>
          
          <button
            onClick={exportAsZip}
            className="px-3 py-1.5 bg-slate-950 hover:bg-slate-800 border border-slate-800 hover:border-slate-700 text-xs text-indigo-400 hover:text-indigo-300 rounded-lg transition-all flex items-center gap-1.5 cursor-pointer font-bold"
          >
            <Download className="w-3.5 h-3.5" />
            Export ZIP
          </button>

          <button
            onClick={() => {
              runWorkspace();
              setActiveTab('preview');
            }}
            className="px-4 py-1.5 bg-gradient-to-r from-emerald-500 to-cyan-600 hover:from-emerald-400 hover:to-cyan-500 text-white text-xs font-bold rounded-lg transition-all flex items-center gap-1.5 shadow-lg shadow-emerald-500/10 cursor-pointer"
          >
            <Play className="w-3.5 h-3.5 fill-white" />
            Run
          </button>
        </div>
      </div>

    </div>
  );
}
